####################################
########  AEROSPACE CONFIG  ########
########  LUKAS LINDNER     ########
####################################




#######  BASICS & LAYOUT  #######

# AFTER LOGIN
# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# AFTER STARTUP
# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
#after-startup-command = ['exec-and-forget /usr/local/bin/sketchybar']
after-startup-command = [
  'exec-and-forget /usr/local/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=7.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focused-monitor-changed = ['move-mouse window-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Notify Sketchybar about workspace change
#exec-on-workspace-change = ['/bin/bash', '-c',
#    '/usr/local/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
#]

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 16
    inner.vertical =   16
    outer.left =       16
    outer.bottom =     16
    outer.top =        16 # with sketchybar: 56
    outer.right =      16







#######  ASSIGNMENTS  #######

#######  WORKSPACE TO MONITOR ASSIGNMENT  #######
# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    6 = 'DELL'
    7 = 'DELL'
    8 = 'DELL'
    9 = 'DELL'  
    10 = 'DELL'


#######  APP WINDOW ASSIGNMENT #######
# See: https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
# And also: https://nikitabobko.github.io/AeroSpace/goodies#popular-apps-ids

# Mail
[[on-window-detected]]
    if.app-id = 'com.apple.mail'
    run = 'move-node-to-workspace 6'

# WhatsApp
[[on-window-detected]]
    if.app-id = 'net.whatsapp.WhatsApp'
    run = 'move-node-to-workspace 6'

# Calendar
[[on-window-detected]]
    if.app-id = 'com.apple.iCal'
    run = 'move-node-to-workspace 7'

# Finamp
[[on-window-detected]]
    if.app-id = 'com.lukaslindner.finamp-macos-debug'
    run = 'move-node-to-workspace 8'

# iOS Simulator
[[on-window-detected]]
    if.app-id = 'com.apple.iphonesimulator'
    run = 'layout floating'






#######  KEYBOARD SHORTCUTS  #######

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # Infos about Binding Modes: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
    # See: https://nikitabobko.github.io/AeroSpace/commands#mode




########  MAIN MODE  ########
# Shortcuts for window management
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    ########  OTHER SHORTCUT MODES  ########
    ctrl-alt-shift-space = 'mode launch'


    
    ########  NODES  ########

    # FOCUS
    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-ctrl-left = 'focus left --boundaries all-monitors-outer-frame'
    alt-ctrl-down = 'focus down --boundaries all-monitors-outer-frame'
    alt-ctrl-up = 'focus up --boundaries all-monitors-outer-frame'
    alt-ctrl-right = 'focus right --boundaries all-monitors-outer-frame'

    # MOVE
    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-ctrl-shift-left = 'move left --boundaries all-monitors-outer-frame'
    alt-ctrl-shift-down = 'move down --boundaries all-monitors-outer-frame'
    alt-ctrl-shift-up = 'move up --boundaries all-monitors-outer-frame'
    alt-ctrl-shift-right = 'move right --boundaries all-monitors-outer-frame'

    # JOIN
    # See https://nikitabobko.github.io/AeroSpace/commands#join-with
    alt-ctrl-shift-cmd-left = 'join-with left'
    alt-ctrl-shift-cmd-down = 'join-with down'
    alt-ctrl-shift-cmd-up = 'join-with up'
    alt-ctrl-shift-cmd-right = 'join-with right'

    # RESIZE & NODE LAYOUT
    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    # See: https://nikitabobko.github.io/AeroSpace/commands#balance-sizes
    # See: https://nikitabobko.github.io/AeroSpace/commands#flatten-workspace-tree
    # See: https://nikitabobko.github.io/AeroSpace/commands#fullscreen
    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-ctrl-comma = 'resize smart -50'
    alt-ctrl-period = 'resize smart +50'
    alt-ctrl-shift-comma = 'balance-sizes'
    alt-ctrl-shift-period = 'flatten-workspace-tree'
    alt-ctrl-shift-f = 'fullscreen'
    alt-ctrl-shift-l = 'layout floating tiling'



    ########  WORKSPACES  ########

    # FOCUS / SHOW
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-ctrl-1 = 'workspace 1'
    alt-ctrl-2 = 'workspace 2'
    alt-ctrl-3 = 'workspace 3'
    alt-ctrl-4 = 'workspace 4'
    alt-ctrl-5 = 'workspace 5'
    alt-ctrl-6 = 'workspace 6'
    alt-ctrl-7 = 'workspace 7'
    alt-ctrl-8 = 'workspace 8'
    alt-ctrl-9 = 'workspace 9'
    alt-ctrl-0 = 'workspace 10'

    # MOVE NODE TO WORKSPACE AND FOCUS
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-ctrl-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-ctrl-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-ctrl-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-ctrl-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-ctrl-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-ctrl-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-ctrl-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-ctrl-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-ctrl-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-ctrl-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

    # MOVE NODE TO WORKSPACE BUT STAY
	  cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
	  cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
	  cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
	  cmd-ctrl-shift-4 = 'move-node-to-workspace 4'
	  cmd-ctrl-shift-5 = 'move-node-to-workspace 5'
	  cmd-ctrl-shift-6 = 'move-node-to-workspace 6'
	  cmd-ctrl-shift-7 = 'move-node-to-workspace 7'
	  cmd-ctrl-shift-8 = 'move-node-to-workspace 8'
	  cmd-ctrl-shift-9 = 'move-node-to-workspace 9'
    cmd-ctrl-shift-0 = 'move-node-to-workspace 10'

    # TOGGLE BETWEEN TWO WORKSPACES
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-ctrl-tab = 'workspace-back-and-forth'







########  LAUNCH MODE  ########
# Shortcuts to launch apps or run scripts
[mode.launch.binding]

    ########  EXIT MODE  ########
	  ctrl-alt-shift-esc = 'mode main'

    ########  CONFIG  ########
    ctrl-alt-shift-comma = ['exec-and-forget open /path/to/aerospace/aerospace.toml', 'mode main'] # Open Config
    ctrl-alt-shift-period = ['reload-config', 'mode main'] # Reload Config

    ########  APPLICATIONS  ########
	  ctrl-alt-shift-t = ['exec-and-forget osascript /path/to/aerospace/scripts/ghostty_terminal.scpt', 'mode main'] # Terminal
	  ctrl-alt-shift-f = ['exec-and-forget osascript /path/to/aerospace/scripts/finder.scpt', 'mode main'] # Finder
    ctrl-alt-shift-b = ['exec-and-forget osascript /path/to/aerospace/scripts/brave.scpt', 'mode main'] # Brave
    ctrl-alt-shift-w = ['exec-and-forget osascript /path/to/aerospace/scripts/librewolf.scpt', 'mode main'] # LibreWolf
    ctrl-alt-shift-c = ['exec-and-forget open /Applications/WhatsApp.app', 'mode main'] # WhatsApp
    ctrl-alt-shift-l = ['exec-and-forget open "/Applications/Logic Pro X.app"', 'mode main'] # Logic
    ctrl-alt-shift-d = ['exec-and-forget open "/Applications/Dorico 6.app"', 'mode main'] # Dorico
    ctrl-alt-shift-m = ['exec-and-forget osascript /path/to/aerospace/scripts/mail.scpt', 'mode main'] # Mail
    ctrl-alt-shift-k = ['exec-and-forget osascript /path/to/aerospace/scripts/calendar.scpt', 'mode main'] # Calendar
    ctrl-alt-shift-e = ['exec-and-forget open "/Applications/Visual Studio Code.app"', 'mode main'] # VS Code

    ########  SCRIPTS  ########
    ctrl-alt-shift-s = ['exec-and-forget osascript /path/to/aerospace/scripts/ssh_sessions_ghostty.scpt', 'mode main'] # SSH Sessions

